# Generated by Django 3.0.4 on 2020-04-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name='bear',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bears', to='api.Category'),
=======
            model_name='recipe',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='api.Category'),
>>>>>>> c0672d92e226b98bfa56946c7ae43d75e2461837
        ),
    ]
