# Generated by Django 3.0.4 on 2020-04-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200421_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='first_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='second_image',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='third_image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
